# Generated by Django 4.0.4 on 2022-05-25 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Joined Date')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('type', models.CharField(choices=[('Advertising Award', 'Advertising Award'), ('Movie/Drama Award', 'Movie/Drama Award'), ('MV Award', 'MV Award'), ('Other awards', 'Other awards')], default='Movie/Drama Award', max_length=255)),
                ('year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='year')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, choices=[('staff', 'staff'), ('client', 'client')], max_length=20, null=True)),
                ('family_name_in_kanji', models.CharField(max_length=255, null=True, verbose_name='Family Name in Kanji')),
                ('first_name_in_kanji', models.CharField(max_length=255, null=True, verbose_name='First Name in Kanji')),
                ('family_name_in_hiragana', models.CharField(max_length=255, null=True, verbose_name='Family Name in Hiragana')),
                ('first_name_in_hiragana', models.CharField(max_length=255, null=True, verbose_name='First Name in Hiragana')),
                ('family_name_in_english', models.CharField(max_length=255, null=True, verbose_name='Family Name in English')),
                ('first_name_in_english', models.CharField(max_length=255, null=True, verbose_name='First Name in English')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True, verbose_name='Gender')),
                ('profile_pic', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='profile_pic/', verbose_name='Profile Picture')),
                ('profile_picture_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('birth_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Birth City')),
                ('current_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Current City')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company')),
                ('working_as', models.CharField(blank=True, max_length=255, null=True, verbose_name='Working As')),
                ('position', models.CharField(max_length=255, null=True, verbose_name='Position')),
                ('is_upgraded', models.BooleanField(default=False, verbose_name='Upgraded')),
                ('full_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Address')),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manager Name')),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone Number')),
                ('employee', models.CharField(max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Detail')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('verified', models.BooleanField(default=False)),
                ('number_of_login', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of Login')),
                ('password_changed_date', models.DateTimeField(blank=True, null=True, verbose_name='Password Changed Date')),
                ('information_agree', models.BooleanField(default=False, verbose_name='Terms and Conditions')),
                ('award', models.ManyToManyField(blank=True, null=True, related_name='award_profiles', to='users.award')),
                ('language', models.ManyToManyField(blank=True, null=True, related_name='language_profiles', to='staff.language', verbose_name='Language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
